/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

#include "version.h"
const char *version_string = "1.18";
const char *compilation_string = "gcc -std=gnu99 -g -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../lib -I../lib -I/usr/local/include -DHAVE_LIBGNUTLS -DNDEBUG ";
const char *link_string = "gcc -std=gnu99 -g -I/usr/local/include -DHAVE_LIBGNUTLS -DNDEBUG -lnettle -L/usr/local/lib -lgnutls -lz ftp-opie.o gnutls.o http-ntlm.o ../lib/libgnu.a";
